---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello from Playbook 2!"

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts 
